pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven {
            name = "Mozilla Nightly"
            url = uri("https://nightly.maven.mozilla.org/maven2")
        }
        maven {
            name = "Mozilla Releases"
            url = uri("https://maven.mozilla.org/maven2/")
        }
    }
}

rootProject.name = "BombachaNavegador"
include ':app'
